-- Supabase schema for hybrid dual-write mode
-- Run this in Supabase SQL Editor before enabling HYBRID_MODE=dual_write in production.

-- ─────────────────────────────────────────────────────────────────────────────
-- Log integrity anchor table (self-contained tamper detection — no Polygon needed)
-- A SHA-256 fingerprint of each day's .log file is stored here after every
-- attendance submission.  Being on a completely separate system (Supabase) means
-- tampering would require compromising BOTH Azure and Supabase simultaneously.
-- ─────────────────────────────────────────────────────────────────────────────
create table if not exists public.log_anchors (
  id           bigint generated by default as identity primary key,
  date         date        not null,
  course       text        not null default 'General',
  log_hash     text        not null,   -- SHA-256 of the full .log file at anchor time
  chain_hash   text,                   -- SHA-256 tip of attendance_chain.json at anchor time
  anchored_at  timestamptz not null default now(),
  server_id    text,
  created_at   timestamptz not null default now()
);

create index if not exists idx_log_anchors_date   on public.log_anchors (date desc);
create index if not exists idx_log_anchors_course on public.log_anchors (course);

alter table public.log_anchors enable row level security;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'log_anchors'
    and policyname = 'service_role_all_log_anchors'
  ) then
    create policy service_role_all_log_anchors
      on public.log_anchors for all to service_role
      using (true) with check (true);
  end if;
end $$;


-- Attendance records mirrored from submit.php
create table if not exists public.attendance_logs (
  id bigint generated by default as identity primary key,
  timestamp timestamptz not null default now(),
  name text not null,
  matric text not null,
  action text not null check (action in ('checkin','checkout')),
  fingerprint text,
  ip text,
  mac text,
  user_agent text,
  course text,
  reason text,
  chain_hash text,
  created_at timestamptz not null default now()
);

create index if not exists idx_attendance_logs_timestamp on public.attendance_logs (timestamp desc);
create index if not exists idx_attendance_logs_matric on public.attendance_logs (matric);
create index if not exists idx_attendance_logs_action on public.attendance_logs (action);
create index if not exists idx_attendance_logs_course on public.attendance_logs (course);
create unique index if not exists uq_attendance_logs_chain_hash on public.attendance_logs (chain_hash) where chain_hash is not null;

-- Support tickets mirrored from support.php
create table if not exists public.support_tickets (
  id bigint generated by default as identity primary key,
  timestamp timestamptz not null default now(),
  name text not null,
  matric text not null,
  message text not null,
  fingerprint text,
  ip text,
  created_at_local text,
  resolved boolean not null default false,
  created_at timestamptz not null default now()
);

create index if not exists idx_support_tickets_timestamp on public.support_tickets (timestamp desc);
create index if not exists idx_support_tickets_matric on public.support_tickets (matric);
create index if not exists idx_support_tickets_resolved on public.support_tickets (resolved);

-- Admin audit records mirrored from admin/state_helpers.php
create table if not exists public.admin_audit_logs (
  id bigint generated by default as identity primary key,
  timestamp timestamptz not null default now(),
  admin_user text not null,
  admin_role text,
  ip_address text,
  category text not null,
  action text not null,
  details text,
  created_at timestamptz not null default now()
);

create index if not exists idx_admin_audit_logs_timestamp on public.admin_audit_logs (timestamp desc);
create index if not exists idx_admin_audit_logs_admin_user on public.admin_audit_logs (admin_user);
create index if not exists idx_admin_audit_logs_category on public.admin_audit_logs (category);
create index if not exists idx_admin_audit_logs_action on public.admin_audit_logs (action);

-- Request timing records matching request_timing.php payload shape.
-- Current code writes timings to JSONL on storage; this table is ready if/when you mirror them to Supabase.
create table if not exists public.request_timings (
  id bigint generated by default as identity primary key,
  route text not null,
  started_at_epoch double precision not null,
  finished_at timestamptz,
  duration_ms numeric(12,2) not null,
  method text,
  uri text,
  status_code integer,
  memory_peak_mb numeric(10,2),
  meta jsonb not null default '{}'::jsonb,
  spans jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists idx_request_timings_route on public.request_timings (route);
create index if not exists idx_request_timings_finished_at on public.request_timings (finished_at desc);
create index if not exists idx_request_timings_status_code on public.request_timings (status_code);
create index if not exists idx_request_timings_duration_ms on public.request_timings (duration_ms desc);
create index if not exists idx_request_timings_meta_gin on public.request_timings using gin (meta);
create index if not exists idx_request_timings_spans_gin on public.request_timings using gin (spans);

-- Optional: keep RLS enabled for defense-in-depth.
-- Service-role writes from backend bypass RLS automatically,
-- but these policies are included for clarity if anon/auth access is added later.
alter table public.attendance_logs enable row level security;
alter table public.support_tickets enable row level security;
alter table public.admin_audit_logs enable row level security;
alter table public.request_timings enable row level security;

do $$
begin
  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public' and tablename = 'attendance_logs' and policyname = 'service_role_all_attendance_logs'
  ) then
    create policy service_role_all_attendance_logs
      on public.attendance_logs
      for all
      to service_role
      using (true)
      with check (true);
  end if;

  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public' and tablename = 'support_tickets' and policyname = 'service_role_all_support_tickets'
  ) then
    create policy service_role_all_support_tickets
      on public.support_tickets
      for all
      to service_role
      using (true)
      with check (true);
  end if;

  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public' and tablename = 'admin_audit_logs' and policyname = 'service_role_all_admin_audit_logs'
  ) then
    create policy service_role_all_admin_audit_logs
      on public.admin_audit_logs
      for all
      to service_role
      using (true)
      with check (true);
  end if;

  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public' and tablename = 'request_timings' and policyname = 'service_role_all_request_timings'
  ) then
    create policy service_role_all_request_timings
      on public.request_timings
      for all
      to service_role
      using (true)
      with check (true);
  end if;
end $$;
