-- Supabase schema for hybrid dual-write mode
-- Run this in Supabase SQL Editor before enabling HYBRID_MODE=dual_write in production.

-- Attendance records mirrored from submit.php
create table if not exists public.attendance_logs (
  id bigint generated by default as identity primary key,
  timestamp timestamptz not null default now(),
  name text not null,
  matric text not null,
  action text not null check (action in ('checkin','checkout')),
  fingerprint text,
  ip text,
  mac text,
  user_agent text,
  course text,
  reason text,
  chain_hash text,
  created_at timestamptz not null default now()
);

create index if not exists idx_attendance_logs_timestamp on public.attendance_logs (timestamp desc);
create index if not exists idx_attendance_logs_matric on public.attendance_logs (matric);
create index if not exists idx_attendance_logs_action on public.attendance_logs (action);
create index if not exists idx_attendance_logs_course on public.attendance_logs (course);
create unique index if not exists uq_attendance_logs_chain_hash on public.attendance_logs (chain_hash) where chain_hash is not null;

-- Support tickets mirrored from support.php
create table if not exists public.support_tickets (
  id bigint generated by default as identity primary key,
  timestamp timestamptz not null default now(),
  name text not null,
  matric text not null,
  message text not null,
  fingerprint text,
  ip text,
  created_at_local text,
  resolved boolean not null default false,
  created_at timestamptz not null default now()
);

create index if not exists idx_support_tickets_timestamp on public.support_tickets (timestamp desc);
create index if not exists idx_support_tickets_matric on public.support_tickets (matric);
create index if not exists idx_support_tickets_resolved on public.support_tickets (resolved);

-- Optional: keep RLS enabled for defense-in-depth.
-- Service-role writes from backend bypass RLS automatically,
-- but these policies are included for clarity if anon/auth access is added later.
alter table public.attendance_logs enable row level security;
alter table public.support_tickets enable row level security;

do $$
begin
  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public' and tablename = 'attendance_logs' and policyname = 'service_role_all_attendance_logs'
  ) then
    create policy service_role_all_attendance_logs
      on public.attendance_logs
      for all
      to service_role
      using (true)
      with check (true);
  end if;

  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public' and tablename = 'support_tickets' and policyname = 'service_role_all_support_tickets'
  ) then
    create policy service_role_all_support_tickets
      on public.support_tickets
      for all
      to service_role
      using (true)
      with check (true);
  end if;
end $$;
