name: 🐛 Bug Report
description: Report a bug or unexpected behavior in the attendance system
title: "[Bug]: "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please fill out the form below to help us investigate and fix the issue.

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: Describe the bug...
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Enter '...'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: Describe what should happen...
    validations:
      required: true

  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual Behavior
      description: What actually happened?
      placeholder: Describe what actually happened...
    validations:
      required: true

  - type: dropdown
    id: component
    attributes:
      label: Component Affected
      description: Which part of the system is affected?
      options:
        - Check-in/Check-out
        - Admin Panel
        - Log Management
        - Email Export
        - Course Management
        - Support Tickets
        - Announcements
        - Blockchain Verification
        - Fingerprint Authentication
        - Other
    validations:
      required: true

  - type: input
    id: php-version
    attributes:
      label: PHP Version
      description: What version of PHP are you using?
      placeholder: "e.g., 8.1.2"
    validations:
      required: true

  - type: dropdown
    id: environment
    attributes:
      label: Environment
      description: Where is the system running?
      options:
        - PHP Built-in Server
        - XAMPP
        - WAMP
        - Apache
        - Nginx
        - Other
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      description: What OS are you using?
      options:
        - Windows
        - macOS
        - Linux
        - Other
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem
      placeholder: Drag and drop images here...

  - type: textarea
    id: logs
    attributes:
      label: Error Logs
      description: If applicable, include relevant error logs or console output
      placeholder: Paste error logs here...
      render: shell

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context about the problem here
      placeholder: Any additional information...

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: Please confirm the following
      options:
        - label: I have checked existing issues to avoid duplicates
          required: true
        - label: I have read the [CONTRIBUTING.md](https://github.com/MAVIS-creator/Blockchain-Based-Attendance-System/blob/main/CONTRIBUTING.md) guidelines
          required: true
        - label: This bug is reproducible
          required: false
