name: ❓ Question or Support
description: Ask a question or get help with the attendance system
title: "[Question]: "
labels: ["question", "support"]
body:
  - type: markdown
    attributes:
      value: |
        Have a question or need support? We're here to help! Please provide details below.

  - type: textarea
    id: question
    attributes:
      label: Your Question
      description: What would you like to know?
      placeholder: Ask your question...
    validations:
      required: true

  - type: dropdown
    id: category
    attributes:
      label: Category
      description: What is your question about?
      options:
        - Installation & Setup
        - Configuration
        - Usage & Features
        - Troubleshooting
        - Security
        - Blockchain Integration
        - Email Configuration
        - Course Management
        - Log Management
        - Deployment
        - Best Practices
        - Other
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Context
      description: Provide any relevant context or background information
      placeholder: |
        - What are you trying to achieve?
        - What have you tried so far?
        - Any relevant configuration or environment details?

  - type: input
    id: php-version
    attributes:
      label: PHP Version (if relevant)
      description: What version of PHP are you using?
      placeholder: "e.g., 8.1.2"

  - type: dropdown
    id: environment
    attributes:
      label: Environment (if relevant)
      description: Where is the system running?
      options:
        - Not applicable
        - PHP Built-in Server
        - XAMPP
        - WAMP
        - Apache
        - Nginx
        - Production Server
        - Other

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots or Code Snippets
      description: If applicable, add screenshots or code snippets
      placeholder: Drag and drop images or paste code here...

  - type: textarea
    id: additional-info
    attributes:
      label: Additional Information
      description: Any other information that might be helpful
      placeholder: Any additional details...

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: Please confirm the following
      options:
        - label: I have checked the [README](https://github.com/MAVIS-creator/Blockchain-Based-Attendance-System/blob/main/README.md) and [QUICKSTART](https://github.com/MAVIS-creator/Blockchain-Based-Attendance-System/blob/main/QUICKSTART.md) documentation
          required: true
        - label: I have searched for similar questions in existing issues
          required: true
