<?php
if (session_status() === PHP_SESSION_NONE) session_start();
if (empty($_SESSION['admin_logged_in'])) {
  header('Location: login.php');
  exit;
}

// Gather tokens from blocked_tokens.log (generated when tab-fencing/inactivity fires)
require_once __DIR__ . '/../storage_helpers.php';
app_storage_init();
$blockedFile = app_storage_file('logs/blocked_tokens.log');
$tokens = [];
if (file_exists($blockedFile)) {
  $lines = file($blockedFile, FILE_IGNORE_NEW_LINES | FILE_SKIP_EMPTY_LINES);
  foreach ($lines as $line) {
    $parts = array_map('trim', explode('|', $line));
    // expected: timestamp | token | fingerprint | ip | mac | userAgent | reason
    if (count($parts) < 2) continue;
    $timestamp = $parts[0] ?? '';
    $token = $parts[1] ?? '';
    $fingerprint = $parts[2] ?? '';
    $ip = $parts[3] ?? '';
    $mac = $parts[4] ?? '';
    // optional: userAgent and reason at 5,6
    if ($token === '') continue;
    if (!isset($tokens[$token])) {
      $tokens[$token] = ['first' => $timestamp, 'last' => $timestamp, 'ips' => [], 'macs' => [], 'matrics' => [], 'count' => 0, 'sample_fp' => $fingerprint];
    }
    $tokens[$token]['count']++;
    if ($timestamp && ($tokens[$token]['first'] === '' || strtotime($timestamp) < strtotime($tokens[$token]['first']))) $tokens[$token]['first'] = $timestamp;
    if ($timestamp && ($tokens[$token]['last'] === '' || strtotime($timestamp) > strtotime($tokens[$token]['last']))) $tokens[$token]['last'] = $timestamp;
    if ($ip) $tokens[$token]['ips'][$ip] = true;
    if ($mac) $tokens[$token]['macs'][$mac] = true;
  }
}
// simplify sets to lists
foreach ($tokens as $k => &$v) {
  $v['ips'] = array_keys($v['ips']);
  $v['macs'] = array_keys($v['macs']);
  $v['matrics'] = array_keys($v['matrics']);
}
unset($v);
?>

<div style="max-width:1000px;margin:0 auto;">
  <div style="margin-bottom:24px;">
    <h2 style="font-size:1.5rem;font-weight:800;color:var(--on-surface);letter-spacing:-0.02em;margin:0;">
      <span class="material-symbols-outlined" style="vertical-align:middle;margin-right:8px;">no_accounts</span>Clear & Revoke Tokens
    </h2>
    <p style="color:var(--on-surface-variant);font-size:0.88rem;margin:4px 0 0;">Manage device blocks and active tokens generated by tab-fencing or inactivity security checks.</p>
  </div>

  <div style="display:flex;gap:20px;flex-wrap:wrap;align-items:flex-start;margin-bottom:24px;">

    <!-- Revoke Token Card -->
    <div class="st-card" style="flex:1;min-width:280px;border-color:var(--primary-container);">
      <h3 style="margin:0 0 8px;font-size:1.1rem;color:var(--primary);display:flex;align-items:center;gap:6px;">
        <span class="material-symbols-outlined" style="font-size:1.2rem;">gpp_bad</span> Revoke Access
      </h3>
      <p style="font-size:0.85rem;color:var(--on-surface-variant);margin:0 0 16px;">Revoke client token, forcing login. Clients must refresh after revocation. Accept token hash, MAC, or IP.</p>

      <div style="display:flex;gap:8px;">
        <input id="revokeToken" type="text" placeholder="token, ip, or mac" style="flex:1;padding:10px 12px;border-radius:8px;border:1px solid var(--outline-variant);background:var(--surface-container-low);color:var(--on-surface);font-family:inherit;font-size:0.9rem;">
        <button id="revokeBtn" class="st-btn st-btn-primary">
          <span class="material-symbols-outlined" style="font-size:1.1rem;">block</span> Revoke
        </button>
      </div>
    </div>

    <!-- Search & Clear Card -->
    <div class="st-card" style="flex:1;min-width:280px;border-color:var(--error-container);">
      <h3 style="margin:0 0 8px;font-size:1.1rem;color:var(--error);display:flex;align-items:center;gap:6px;">
        <span class="material-symbols-outlined" style="font-size:1.2rem;">cleaning_services</span> Clear Device Lock
      </h3>
      <p style="font-size:0.85rem;color:var(--on-surface-variant);margin:0 0 16px;">Remove server-side limits (cooldown, IP lock) for a device. Accept fingerprint or matric.</p>

      <div style="display:flex;gap:8px;">
        <input id="searchKey" type="text" placeholder="fingerprint, matric, ip..." style="flex:1;padding:10px 12px;border-radius:8px;border:1px solid var(--outline-variant);background:var(--surface-container-low);color:var(--on-surface);font-family:inherit;font-size:0.9rem;">
        <button id="searchClearBtn" class="st-btn st-btn-danger">
          <span class="material-symbols-outlined" style="font-size:1.1rem;">delete_sweep</span> Clear
        </button>
      </div>
    </div>

  </div>

  <!-- Known Tokens Table -->
  <div class="st-card" style="padding:0;overflow:hidden;">
    <div style="padding:20px 24px;border-bottom:1px solid var(--outline-variant);display:flex;justify-content:space-between;align-items:center;flex-wrap:wrap;gap:12px;">
      <div>
        <h3 style="margin:0;font-size:1.1rem;color:var(--on-surface);display:flex;align-items:center;gap:6px;">
          <span class="material-symbols-outlined" style="font-size:1.2rem;">history</span> Known Blocked Tokens
        </h3>
        <p style="font-size:0.85rem;color:var(--on-surface-variant);margin:2px 0 0;">Tokens actively recorded in logs due to fencing/inactivity events.</p>
      </div>
      <div style="display:flex;gap:8px;">
        <?php if (count($tokens) > 0): ?>
          <button id="clearAllTokens" class="st-btn st-btn-danger st-btn-sm" title="Clear server locks for all tokens">
            <span class="material-symbols-outlined" style="font-size:1rem;">clear_all</span> Clear All
          </button>
          <button id="revokeAllTokens" class="st-btn st-btn-primary st-btn-sm" title="Revoke all known tokens">
            <span class="material-symbols-outlined" style="font-size:1rem;">gpp_maybe</span> Revoke All
          </button>
        <?php endif; ?>
      </div>
    </div>

    <div style="overflow-x:auto;">
      <?php if (count($tokens) === 0): ?>
        <div style="padding:48px 24px;text-align:center;">
          <span class="material-symbols-outlined" style="font-size:3rem;color:var(--outline-variant);display:block;margin-bottom:8px;">verified_user</span>
          <p style="margin:0;color:var(--on-surface-variant);font-weight:600;">No active device blocks or tokens found.</p>
        </div>
      <?php else: ?>
        <table class="st-table" style="width:100%;">
          <thead>
            <tr>
              <th>Token (Hash)</th>
              <th>First Event</th>
              <th>Last Event</th>
              <th>Count</th>
              <th class="mobile-hide-col">Matched IPs</th>
              <th class="mobile-hide-col">MACs</th>
              <th style="text-align:right;">Actions</th>
            </tr>
          </thead>
          <tbody>
            <?php foreach ($tokens as $token => $info): ?>
              <tr>
                <td style="font-family:monospace;font-size:0.85rem;color:var(--on-surface-variant);max-width:120px;overflow:hidden;text-overflow:ellipsis;" title="<?= htmlspecialchars($token) ?>">
                  <?= htmlspecialchars(substr($token, 0, 16)) ?>…
                </td>
                <td style="font-size:0.85rem;white-space:nowrap;"><?= htmlspecialchars(date('M d, H:i:s', strtotime($info['first']))) ?></td>
                <td style="font-size:0.85rem;white-space:nowrap;"><?= htmlspecialchars(date('M d, H:i:s', strtotime($info['last']))) ?></td>
                <td><span class="st-chip st-chip-neutral"><?= intval($info['count']) ?></span></td>
                <td class="mobile-hide-col" style="font-family:monospace;font-size:0.8rem;color:var(--on-surface-variant);max-width:150px;overflow:hidden;text-overflow:ellipsis;">
                  <?= htmlspecialchars(implode(', ', array_slice($info['ips'], 0, 2))) ?><?= count($info['ips']) > 2 ? '...' : '' ?>
                </td>
                <td class="mobile-hide-col" style="font-family:monospace;font-size:0.8rem;color:var(--on-surface-variant);max-width:150px;overflow:hidden;text-overflow:ellipsis;">
                  <?= htmlspecialchars(implode(', ', array_slice($info['macs'], 0, 1))) ?><?= count($info['macs']) > 1 ? '...' : '' ?>
                </td>
                <td style="text-align:right;white-space:nowrap;">
                  <button class="st-btn st-btn-sm st-btn-primary revoke-token" data-token="<?= htmlspecialchars($token) ?>" style="padding:4px 8px;font-size:0.8rem;">Revoke</button>
                  <button class="st-btn st-btn-sm st-btn-danger clear-token" data-token="<?= htmlspecialchars($token) ?>" style="padding:4px 8px;font-size:0.8rem;margin-left:4px;">Clear</button>
                </td>
              </tr>
            <?php endforeach; ?>
          </tbody>
        </table>
      <?php endif; ?>
    </div>
  </div>

</div>

<script>
  // helper to determine type
  function detectType(v) {
    var ipPattern = /^\d{1,3}(?:\.\d{1,3}){3}$/;
    var macPattern = /^[0-9A-Fa-f:]{6,}$/;
    if (ipPattern.test(v)) return 'ip';
    if (macPattern.test(v)) return 'mac';
    return 'token';
  }

  const Toast = Swal.mixin({
    toast: true,
    position: 'top-end',
    showConfirmButton: false,
    timer: 3000,
    timerProgressBar: true
  });

  document.getElementById('revokeBtn')?.addEventListener('click', function() {
    var v = document.getElementById('revokeToken').value.trim();
    if (!v) {
      Toast.fire({
        icon: 'warning',
        title: 'Enter token/ip/mac'
      });
      return;
    }
    var t = detectType(v);

    window.adminConfirm('Revoke ' + t.toUpperCase(), 'Tokens revoked will cause affected clients to refresh or be logged out. Set expiry in days:', 'warning', {
      input: 'number',
      inputValue: 7,
      inputAttributes: {
        min: 1,
        step: 1
      }
    }).then(function(res) {
      if (!res) return;
      var days = typeof res === 'number' || typeof res === 'string' ? parseInt(res, 10) : 7;
      var body = new URLSearchParams();
      body.append(t, v);
      body.append('days', days);
      if (window.ADMIN_CSRF_TOKEN) body.append('csrf_token', window.ADMIN_CSRF_TOKEN);

      fetch('revoke_entry.php', {
        method: 'POST',
        body: body
      }).then(r => r.json()).then(j => {
        if (j && j.ok) window.adminAlert('Done', 'Revoked added.', 'success');
        else window.adminAlert('Failed', (j && j.message) ? j.message : 'Could not revoke', 'error');
      }).catch(e => window.adminAlert('Error', 'Could not revoke', 'error'));
    });
  });

  document.getElementById('searchClearBtn')?.addEventListener('click', function() {
    var v = document.getElementById('searchKey').value.trim();
    if (!v) {
      Toast.fire({
        icon: 'warning',
        title: 'Enter search key'
      });
      return;
    }
    var t = detectType(v);

    window.adminConfirm('Confirm Clear', 'Clear any entries matching this fingerprint/matric/ip?', 'warning').then(function(ok) {
      if (!ok) return;
      var p = new URLSearchParams();
      if (t === 'ip') p.append('ip', v);
      else if (t === 'mac') p.append('mac', v);
      else {
        // For unknown values, try token and legacy fields so admin can clear mixed stores.
        p.append('token', v);
        p.append('fingerprint', v);
        p.append('matric', v);
      }
      if (window.ADMIN_CSRF_TOKEN) p.append('csrf_token', window.ADMIN_CSRF_TOKEN);
      fetch('clear_device.php', {
        method: 'POST',
        body: p
      }).then(r => r.json()).then(j => {
        if (j && j.ok) window.adminAlert('Cleared', 'Device block removed', 'success');
        else window.adminAlert('Failed', (j && j.message) ? j.message : 'Could not clear', 'error');
      }).catch(e => window.adminAlert('Error', 'Could not clear', 'error'));
    });
  });

  // Per-token Row Actions
  document.querySelectorAll('.clear-token').forEach(function(b) {
    b.addEventListener('click', function() {
      var t = this.getAttribute('data-token');
      if (!t) return;
      window.adminConfirm('Clear & Revoke', 'Clear server-side entries for this token AND revoke it on clients?', 'danger').then(function(ok) {
        if (!ok) return;
        var p1 = new URLSearchParams();
        p1.append('token', t);
        p1.append('days', 7);
        if (window.ADMIN_CSRF_TOKEN) p1.append('csrf_token', window.ADMIN_CSRF_TOKEN);
        fetch('revoke_entry.php', {
          method: 'POST',
          body: p1
        }).then(function() {
          var p2 = new URLSearchParams();
          p2.append('token', t);
          if (window.ADMIN_CSRF_TOKEN) p2.append('csrf_token', window.ADMIN_CSRF_TOKEN);
          return fetch('clear_device.php', {
            method: 'POST',
            body: p2
          });
        }).then(r => r.json()).then(j => {
          window.adminAlert('Done', 'Cleared & Revoked', 'success').then(() => location.reload());
        }).catch(e => window.adminAlert('Error', 'Operation failed', 'error'));
      });
    });
  });

  document.querySelectorAll('.revoke-token').forEach(function(b) {
    b.addEventListener('click', function() {
      var t = this.getAttribute('data-token');
      if (!t) return;
      window.adminConfirm('Revoke token', 'Set expiry (days)', 'warning', {
        input: 'number',
        inputValue: 7
      }).then(function(res) {
        if (!res) return;
        var days = parseInt(res, 10) || 7;
        var p = new URLSearchParams();
        p.append('token', t);
        p.append('days', days);
        if (window.ADMIN_CSRF_TOKEN) p.append('csrf_token', window.ADMIN_CSRF_TOKEN);
        fetch('revoke_entry.php', {
          method: 'POST',
          body: p
        }).then(r => r.json()).then(j => {
          if (j && j.ok) Toast.fire({
            icon: 'success',
            title: 'Revocation added'
          });
          else window.adminAlert('Failed', (j && j.message) ? j.message : 'Could not revoke', 'error');
        }).catch(e => window.adminAlert('Error', 'Could not revoke', 'error'));
      });
    });
  });

  // Bulk Actions
  document.getElementById('clearAllTokens')?.addEventListener('click', function() {
    var tokens = Array.from(document.querySelectorAll('button.clear-token')).map(b => b.getAttribute('data-token'));
    if (!tokens.length) return;
    window.adminConfirm('Clear & Revoke All', 'Clear server-side entries ALL tokens found in logs and revoke them?', 'danger').then(function(ok) {
      if (!ok) return;
      var promises = tokens.map(function(t) {
        var p1 = new URLSearchParams();
        p1.append('token', t);
        p1.append('days', 7);
        if (window.ADMIN_CSRF_TOKEN) p1.append('csrf_token', window.ADMIN_CSRF_TOKEN);
        return fetch('revoke_entry.php', {
          method: 'POST',
          body: p1
        }).then(function() {
          var p2 = new URLSearchParams();
          p2.append('token', t);
          if (window.ADMIN_CSRF_TOKEN) p2.append('csrf_token', window.ADMIN_CSRF_TOKEN);
          return fetch('clear_device.php', {
            method: 'POST',
            body: p2
          });
        }).then(r => r.json());
      });
      Promise.all(promises).then(results => {
        window.adminAlert('Done', 'Cleared all', 'success').then(() => location.reload());
      }).catch(e => window.adminAlert('Error', 'Failed', 'error'));
    });
  });

  document.getElementById('revokeAllTokens')?.addEventListener('click', function() {
    var tokens = Array.from(document.querySelectorAll('button.revoke-token')).map(b => b.getAttribute('data-token'));
    if (!tokens.length) return;
    window.adminConfirm('Revoke All', 'Set expiry (days) for all tokens?', 'warning', {
      input: 'number',
      inputValue: 7
    }).then(function(res) {
      if (!res) return;
      var days = parseInt(res, 10) || 7;
      var promises = tokens.map(function(t) {
        var p = new URLSearchParams();
        p.append('token', t);
        p.append('days', days);
        if (window.ADMIN_CSRF_TOKEN) p.append('csrf_token', window.ADMIN_CSRF_TOKEN);
        return fetch('revoke_entry.php', {
          method: 'POST',
          body: p
        }).then(r => r.json());
      });
      Promise.all(promises).then(results => {
        var failed = results.filter(function(x) {
          return !x || !x.ok;
        });
        if (failed.length) window.adminAlert('Partial failure', 'Some tokens could not be revoked.', 'warning');
        else window.adminAlert('Done', 'Revoked all', 'success');
      }).catch(e => window.adminAlert('Error', 'Failed', 'error'));
    });
  });

  // Try to open SSE connection for immediate revocation push (optional)
  if (typeof(EventSource) !== 'undefined') {
    try {
      var es = new EventSource('revoke_sse.php');
      es.addEventListener('revoked', function(e) {
        try {
          var payload = JSON.parse(e.data);
          if (payload && payload.revoked && payload.revoked.tokens) {
            var myToken = localStorage.getItem('attendance_token');
            if (myToken && payload.revoked.tokens[myToken]) {
              localStorage.removeItem('attendance_token');
              localStorage.removeItem('attendanceBlocked');
              if (window.adminAlert) window.adminAlert('Revoked', 'Your token was revoked by admin. Please reload.', 'info');
            }
          }
        } catch (ignore) {}
      });
    } catch (e) {
      /* ignore, fallback polling remains */ }
  }
</script>
